// Generated by scripts/generate-types.mjs.
// napi-rs native declarations are generated in native.d.ts during npm run build.

export interface LaunchOptions {
  headless?: boolean;
  executablePath?: string;
  channel?: string;
  args?: string[];
  ignoreAllDefaultArgs?: boolean;
  ignoreDefaultArgs?: string[];
  timeout?: number;
  userDataDir?: string;
  env?: Record<string, string | number | boolean>;
  chromiumSandbox?: boolean;
  proxy?: {
    server: string;
    bypass?: string;
    username?: string;
    password?: string;
  };
}

export interface GotoOptions {
  waitUntil?: 'load' | 'domcontentloaded' | 'networkidle' | 'commit';
  timeout?: number;
  referer?: string;
}

export interface ActionOptions {
  timeout?: number;
}

export interface ScreenshotOptions {
  path?: string;
  fullPage?: boolean;
  clip?: { x: number; y: number; width: number; height: number; scale?: number };
  timeout?: number;
  type?: 'png' | 'jpeg' | 'webp';
  quality?: number;
  omitBackground?: boolean;
}

export interface ContextOptions {
  /**
   * Accepted for API compatibility. The current Node engine drives a single
   * Chromium process and cannot toggle certificate handling per context after
   * launch; pass args: ['--ignore-certificate-errors'] to chromium.launch()
   * instead. A one-time warning is emitted when this is set.
   */
  ignoreHTTPSErrors?: boolean;
  /** Default timeout (ms) inherited by pages created from this context. */
  timeout?: number;
  /** Default navigation timeout (ms) inherited by pages created from this context. */
  navigationTimeout?: number;
}

export class Browser {
  newPage(): Promise<Page>;
  /**
   * Compatibility shim: the alpha Node engine is single-process, so contexts do
   * NOT provide the storage/cookie isolation of a real Playwright BrowserContext.
   */
  newContext(options?: ContextOptions): Promise<BrowserContext>;
  contexts(): BrowserContext[];
  close(): Promise<void>;
  wsEndpoint(): string;
}

export class BrowserContext {
  browser(): Browser;
  pages(): Page[];
  newPage(): Promise<Page>;
  setDefaultTimeout(timeout: number): void;
  setDefaultNavigationTimeout(timeout: number): void;
  close(): Promise<void>;
}

export class Page {
  goto(url: string, options?: GotoOptions): Promise<unknown | null>;
  click(selector: string, options?: ActionOptions): Promise<void>;
  fill(selector: string, value: string, options?: ActionOptions): Promise<void>;
  title(options?: ActionOptions): Promise<string>;
  textContent(selector: string, options?: ActionOptions): Promise<string | null>;
  evaluate<T = unknown>(expression: string | ((arg?: unknown) => T | Promise<T>), arg?: unknown, options?: ActionOptions): Promise<T>;
  screenshot(options?: ScreenshotOptions): Promise<Buffer>;
  setDefaultTimeout(timeout: number): void;
  setDefaultNavigationTimeout(timeout: number): void;
  close(options?: { timeout?: number; runBeforeUnload?: boolean }): Promise<void>;
}

export const chromium: {
  launch(options?: LaunchOptions): Promise<Browser>;
  executablePath(): Promise<string>;
};

declare const rustwright: {
  chromium: typeof chromium;
  Browser: typeof Browser;
  BrowserContext: typeof BrowserContext;
  Page: typeof Page;
};

export default rustwright;
