/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function chromiumExecutablePath(): Promise<string | null>
export declare function launchChromium(optionsJson: string): Promise<Browser>
export declare class Browser {
  newPage(): Promise<Page>
  close(): Promise<void>
  wsEndpoint(): string
}
export declare class Page {
  targetId(): string
  setDefaultTimeout(timeout: number): void
  setDefaultNavigationTimeout(timeout: number): void
  setContextDefaultTimeout(timeout: number): void
  setContextDefaultNavigationTimeout(timeout: number): void
  goto(url: string, waitUntil?: string | undefined | null, timeout?: number | undefined | null, referer?: string | undefined | null): Promise<string>
  click(selector: string, timeout?: number | undefined | null): Promise<void>
  fill(selector: string, value: string, timeout?: number | undefined | null): Promise<void>
  title(timeout?: number | undefined | null): Promise<string>
  textContent(selector: string, timeout?: number | undefined | null): Promise<string | null>
  evaluate(expression: string, argJson?: string | undefined | null, timeout?: number | undefined | null): Promise<string>
  screenshot(optionsJson?: string | undefined | null): Promise<Buffer>
  close(timeout?: number | undefined | null, runBeforeUnload?: boolean | undefined | null): Promise<void>
}
